version: "2.1"

services:
    nginx:
        build: ./nginx/
        ports:
            - 80:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
            - "${NGINX_LOG_ROOT}:/var/log/nginx:rw"
        networks:
            - server
        depends_on:
            - php
    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
        networks:
            - database
            - server
        depends_on:
            - mysql
    
    mysql:
        image: mysql:5.7
        volumes:
            - "${MYSQL_DATA_ROOT}:/var/lib/mysql:rw"
        networks:
            - database
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

networks: 
    database:
    server:

